const industries = [
    'Accounting',
    'Management Consulting',
    'Non-Profit Organization Management',
    'Design',
    'Utilities',
    'Mechanical or Industrial Engineering',
    'Environmental Services',
    'Hospital &amp; Health Care',
    'Hospitality',
    'Information Technology and Services',
    'Law Practice',
    'Law Enforcement',
    'Leisure, Travel & Tourism',
    'Marketing and Advertising',
    'Online Media',
    'Construction',
    'Government Administration',
    'Human Resources',
    'Retail',
    'Information Services',
    'Pharmaceuticals',
    'Civic &amp; Social Organization',
    'Higher Education',
    'Transportation/Trucking/Railroad',
    'Gambling &amp; Casinos',
    'Computer Software',
    'Market Research',
    'Airlines/Aviation',
    'Alternative Dispute Resolution',
    'Alternative Medicine',
    'Animation',
    'Apparel &amp; Fashion',
    'Architecture &amp; Planning',
    'Arts and Crafts',
    'Automotive',
    'Aviation &amp; Aerospace',
    'Banking',
    'Biotechnology',
    'Broadcast Media',
    'Building Materials',
    'Business Supplies and Equipment',
    'Capital Markets',
    'Chemicals',
    'Civil Engineering',
    'Commercial Real Estate',
    'Computer &amp; Network Security',
    'Computer Games',
    'Computer Hardware',
    'Computer Networking',
    'Consumer Electronics',
    'Consumer Goods',
    'Consumer Services',
    'Cosmetics',
    'Dairy',
    'Defense &amp; Space',
    'Education Management',
    'E-Learning',
    'Electrical/Electronic Manufacturing',
    'Entertainment',
    'Events Services',
    'Executive Office',
    'Facilities Services',
    'Farming',
    'Financial Services',
    'Fine Art',
    'Fishery',
    'Food &amp; Beverages',
    'Food Production',
    'Fund-Raising',
    'Furniture',
    'Glass, Ceramics & Concrete',
    'Government Relations',
    'Graphic Design',
    'Health, Wellness and Fitness',
    'Import and Export',
    'Individual &amp; Family Services',
    'Industrial Automation',
    'Insurance',
    'International Affairs',
    'International Trade and Development',
    'Internet',
    'Investment Banking',
    'Investment Management',
    'Judiciary',
    'Legal Services',
    'Legislative Office',
    'Libraries',
    'Logistics and Supply Chain',
    'Luxury Goods &amp; Jewelry',
    'Machinery',
    'Maritime',
    'Media Production',
    'Medical Devices',
    'Medical Practice',
    'Mental Health Care',
    'Military',
    'Mining &amp; Metals',
    'Motion Pictures and Film',
    'Museums and Institutions',
    'Music',
    'Nanotechnology',
    'Newspapers',
    'Oil &amp; Energy',
    'Outsourcing/Offshoring',
    'Package/Freight Delivery',
    'Packaging and Containers',
    'Paper &amp; Forest Products',
    'Performing Arts',
    'Philanthropy',
    'Photography',
    'Plastics',
    'Political Organization',
    'Primary/Secondary Education',
    'Printing',
    'Professional Training &amp; Coaching',
    'Program Development',
    'Public Policy',
    'Public Relations and Communications',
    'Public Safety',
    'Publishing',
    'Railroad Manufacture',
    'Ranching',
    'Real Estate',
    'Recreational Facilities and Services',
    'Religious Institutions',
    'Renewables &amp; Environment',
    'Research',
    'Restaurants',
    'Security and Investigations',
    'Semiconductors',
    'Shipbuilding',
    'Sporting Goods',
    'Sports',
    'Staffing and Recruiting',
    'Supermarkets',
    'Telecommunications',
    'Textiles',
    'Think Tanks',
    'Tobacco',
    'Translation and Localization',
    'Venture Capital &amp; Private Equity',
    'Veterinary',
    'Warehousing',
    'Wholesale',
    'Wine and Spirits',
    'Wireless',
    'Writing and Editing'
]

export default industries;
